learnkit/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'learnkit.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^motorapp/', include('motorapp.urls', namespace='motorapp')),
    url(r'^accounts/', include('django.contrib.auth.urls',
                           namespace='accounts')),
]

motorapp/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
        # Motorapp
        url(r'^$', views.welcome, name='welcome'),
        # ex: /motorapp/datasets
        url(r'^dataset/$', views.DatasetList.as_view(), name='dataset'),
        url(r'^dataset/upload/$', views.upload_dataset, name='upload_dataset'),
        url(r'^dataset/run/$', views.run_analysis, name='run'),
]

motorapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Dataset(models.Model):
    """
    :param raw_data: data set (nb_sample, nb_raw_features)
    :param description: problem description

    :type raw_data: FileField, max_length=200, null=True, blank=True
    :type description: CharField, max_length=300, null=True, blank=True
    """
    user = models.ForeignKey(User, null=True, blank=True)
    raw_data = models.FileField(max_length=100, null=True, blank=True)
    description = models.CharField(max_length=300, null=True, blank=True)

    def __unicode__(self):
        return self.description


class Problem(models.Model):
    """Class about the problem table

    :param dataset: associated dataset
    :param pb_type: problem type, can be classification or regression
    :param cost_function: cost function to minimize
    :param target: target data set (nb_sample, nb_target_dim)
    :param description: problem description
    :param train_prop: proportion of training dataset

    :type dataset: ForeignKey(Dataset), max_length=200, null=True, blank=True
    :type pb_type: CharField, choices (CLF or REG), max_length=3, null=True,
    blank=True
    :type cost_function: CharField, max_length=200, null=True, blank=True
    :type target: FileField, max_length=200, null=True, blank=True
    :type description: CharField, max_length=300, null=True, blank=True
    :type train_prop: IntegerField, default=68, null=True, blank=True
    """
    dataset = models.ForeignKey(Dataset, null=True, blank=True)
    PB_CHOICES = (
        ('CLF', 'classification'),
        ('REG', 'regression'),
    )
    pb_type = models.CharField(max_length=3, choices=PB_CHOICES,
                               null=True, blank=True)
    # cost_function = models.CharField(max_length=200, null=True, blank=True)
    # target = models.FileField(max_length=200, null=True, blank=True)
    # description = models.CharField(max_length=300, null=True, blank=True)
    # train_prop = models.IntegerField(default=68, null=True, blank=True)

    def __unicode__(self):
        return self.pb_type  # description


class Features(models.Model):
    """Class about the feature table

    :param data: features (nb_sample, nb_features)
    :param problem: associated problem
    :param description: features description

    :type data: FileField, max_length=200, null=True, blank=True
    :type problem: ForeignKey(Problem), null=True, blank=True
    :type description: CharField, max_length=300, null=True, blank=True
    """
    data = models.FileField(max_length=200, null=True, blank=True)
    problem = models.ForeignKey(Problem, null=True, blank=True)
    description = models.CharField(max_length=300, null=True, blank=True)

    def __unicode__(self):
        return self.description


class Estimator(models.Model):
    """Class about the estimator

    :param name: Estimator's name
    :param data: Estimator's name
    :param dict_param: dictionnary containing estimator parameters
    :param dict_perf: dictionnary containing estimator pierformances

    :type name: CharField, max_length=20, null+True, blank=True
    :type name: CharField, max_length=20, null+True, blank=True
    :type dict_param: FileField, max_length=200, null=True, blank=True
    :type dict_perf: FileField, max_length=200, null=True, blank=True
    """
    name = models.CharField(max_length=20, null=True, blank=True)
    data = models.ForeignKey(Features, null=True, blank=True)
    dict_param = models.FileField(max_length=200, null=True, blank=True)
    dict_score = models.FileField(max_length=200, null=True, blank=True)

    def __unicode__(self):
        return self.name

motorapp/forms.py
from django import forms
from django.forms import ModelForm
from motorapp.models import Problem


class UploadFileForm(forms.Form):
    # we do not use a ModelForm based on Dataset, since what is uploaded may
    # need to be modified before saving it as a dataset
    description = forms.CharField(max_length=300, label='Describe the dataset \
                                  content', help_text='blabla max: 300 char')
    file = forms.FileField(max_length=100, label='Select a dataset file',
                           help_text='Read uploading instructions...')


class ProblemForm(ModelForm):
    class Meta:
        model = Problem
        fields = ['dataset', 'pb_type']

motorapp/views.py
from django.shortcuts import render, render_to_response, redirect
from django.template import RequestContext
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
from motorapp.models import Dataset, Problem
from .forms import UploadFileForm, ProblemForm
import task


def welcome(request):
    context = {'main_info': 'oh yeah'}
    return render(request, 'motorapp/welcome.html', context)


class DatasetList(ListView):
    template_name = 'motorapp/list_dataset.html'
    model = Dataset
    context_object_name = 'dataset'


@login_required
def upload_dataset(request):
    context = {}
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            if not Dataset.objects.filter(description=form.
                                          cleaned_data['description']):
                newdataset = Dataset(description=form.
                                     cleaned_data['description'],
                                     raw_data=request.FILES['file'],
                                     user=request.user)
                newdataset.save()
                return redirect("motorapp:run")
            else:
                context['error'] = 'Oups, your dataset has not been uploaded, \
                                    since this description already exists, \
                                    change it!'
    else:
        form = UploadFileForm()
    context['form'] = form
    return render_to_response('motorapp/upload_dataset.html', context,
                              context_instance=RequestContext(request))


@login_required
def run_analysis(request):
    context = {}
    # context['list_dataset'] = Dataset.object.filter(user=request.user)
    if request.method == 'POST':
        form = ProblemForm(request.POST)
        if form.is_valid():
            newproblem = Problem(dataset=form.cleaned_data['dataset'],
                                 pb_type=form.cleaned_data['pb_type'])
            newproblem.save()
            context['success'] = 'Oh yeah'
            score = task.train_test(newproblem.dataset.raw_data.path,
                                    newproblem.pb_type)
            print score
            context['score'] = score
        else:
            context['error'] = 'problem in problem'
    else:
        form = ProblemForm()
        form.fields["dataset"].queryset = Dataset.objects.\
            filter(user=request.user)
    context['form'] = form
    return render_to_response('motorapp/run_analysis.html', context,
                              context_instance=RequestContext(request))

motorapp/templates/motorapp/list_dataset.html
{% extends "base.html" %}

{% load staticfiles %}

{% block header %}

Oh yeah

{% endblock header %}

{% block content %}

<div class="row">
    <div class="col-lg-12">
    youp youp
    </div><!-- /col-lg-12 -->
</div><!-- /row -->

{% endblock content %}

{% block scripts %}


{% endblock scripts %}

motorapp/templates/motorapp/run_analysis.html
{% extends "base.html" %}

{% load staticfiles %}

{% block header %}

Choose your Dataset!

{% endblock header %}

{% block content %}

<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card"> 
        <div class="card-body">
            <div class="panel fresh-color panel-warning">
                <div class="panel-heading">
                    <b>Define your problem:</b>
                </div>
                <div class="panel-body">
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-body">
                    <form action="{% url 'motorapp:run' %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                                {{ form.as_p }}
                            </p>
                            {% if error %}
                                <p><font color="#FA2A00">{{ error }}</font></p>
                            {% endif %}
                            {% if success %}
                                <p>Spoon score: {{ score }} </p>
                            {% endif %}
                            <p><input type="submit" value="Run!" /></p>
                     </form>
                 </div>
            </div> 
        </div>
    </div>
</div>
{% endblock content %}

motorapp/templates/motorapp/upload_dataset.html
{% extends "base.html" %}

{% load staticfiles %}

{% block header %}

Upload your Dataset!

{% endblock header %}

{% block content %}

<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card"> 
        <div class="card-body">
            <div class="panel fresh-color panel-warning">
                <div class="panel-heading">
                    <b>Supported file format:</b>
                </div>
                <div class="panel-body">
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-body">
                    <form action="{% url 'motorapp:upload_dataset' %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <p>{{ form.file.label_tag }} 
                                {{ form.file.errors }}
                                {{ form.file }}
                            </p>
                            <p>
                                {{ form.description.label_tag }} {{ form.description.help_text }}  
                                {{ form.description }}
                            </p>
                            <p>
                                {{ form.pb_type.label_tag }}   
                                {{ form.pb_type }}
                            </p>
                            {% if error %}
                                <p><font color="#FA2A00">{{ error }}</font></p>
                            {% endif %}
                            {% if success %}
                                <p><font color="#FA2A00">{{ success }}</font></p>
                                <p>Spoon score: {{ score }} </p>
                            {% endif %}
                            <p><input type="submit" value="Upload your dataset!" /></p>
                     </form>
                 </div>
            </div> 
        </div>
    </div>
</div>
{% endblock content %}

motorapp/templates/motorapp/welcome.html
{% extends "base.html" %}

{% load staticfiles %}

{% block header %}

What is it?

{% endblock header %}

{% block content %}

<div class="row">
    <div class="col-lg-12">
    LearnKit is blablabla
    </div><!-- /col-lg-12 -->
</div><!-- /row -->

{% endblock content %}

{% block scripts %}


{% endblock scripts %}

templates/base.html
<!DOCTYPE html>
<html>

<head>
    <title>LearnKit</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:300,400' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,900' rel='stylesheet' type='text/css'>
    <!-- CSS Libs -->
    <link rel="stylesheet" type="text/css" href="/static/motorapp/bower_components/bootstrap/dist/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="/static/motorapp/bower_components/fontawesome/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="/static/motorapp/bower_components/animate.css/animate.css">
    <link rel="stylesheet" type="text/css" href="/static/motorapp/bower_components/bootstrap-switch/dist/css/bootstrap3/bootstrap-switch.min.css">
    <link rel="stylesheet" type="text/css" href="/static/motorapp/bower_components/iCheck/skins/flat/_all.css">
    <link rel="stylesheet" type="text/css" href="/static/motorapp/bower_components/DataTables/media/css/jquery.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="/static/motorapp/bower_components/select2/dist/css/select2.min.css">
    <link rel="stylesheet" type="text/css" href="/static/motorapp/vendor/css/dataTables.bootstrap.css">
    <!-- CSS App -->
    <link rel="stylesheet" type="text/css" href="/static/motorapp/css/style.css">
    <link rel="stylesheet" type="text/css" href="/static/motorapp/css/themes.css">
</head>

<body class="flat-blue">
    <div class="app-container">
        <div class="row content-container">
            <nav class="navbar navbar-default navbar-fixed-top navbar-top">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-expand-toggle">
                            <i class="fa fa-bars icon"></i>
                        </button>
                        <ol class="breadcrumb navbar-breadcrumb">
                            <li>LearnKit</li>
<!--                             <li class="active">Static Table</li> -->
                        </ol>
                        <button type="button" class="navbar-right-expand-toggle pull-right visible-xs">
                            <i class="fa fa-th icon"></i>
                        </button>
                    </div>
<!--                     <ul class="nav navbar-nav navbar-right"> -->
<!--                         <button type="button" class="navbar-right-expand-toggle pull-right visible-xs"> -->
<!--                        <i class="fa fa-times icon"></i>  -->
<!--                         </button> -->
<!--                         <li class="dropdown"> -->
<!--                             <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-comments-o"></i></a> -->
<!--                             <ul class="dropdown-menu animated fadeInDown"> -->
<!--                                 <li class="title"> -->
<!--                                     Notification <span class="badge pull-right">0</span> -->
<!--                                 </li> -->
<!--                                 <li class="message"> -->
<!--                                     No new notification -->
<!--                                 </li> -->
<!--                             </ul> -->
<!--                         </li> -->
<!--                         <li class="dropdown danger"> -->
<!--                             <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-star-half-o"></i> 4</a> -->
<!--                             <ul class="dropdown-menu danger  animated fadeInDown"> -->
<!--                                 <li class="title"> -->
<!--                                     Notification <span class="badge pull-right">4</span> -->
<!--                                 </li> -->
<!--                                 <li> -->
<!--                                     <ul class="list-group notifications"> -->
<!--                                         <a href="#"> -->
<!--                                             <li class="list-group-item"> -->
<!--                                                 <span class="badge">1</span> <i class="fa fa-exclamation-circle icon"></i> new registration -->
<!--                                             </li> -->
<!--                                         </a> -->
<!--                                         <a href="#"> -->
<!--                                             <li class="list-group-item"> -->
<!--                                                 <span class="badge success">1</span> <i class="fa fa-check icon"></i> new orders -->
<!--                                             </li> -->
<!--                                         </a> -->
<!--                                         <a href="#"> -->
<!--                                             <li class="list-group-item"> -->
<!--                                                 <span class="badge danger">2</span> <i class="fa fa-comments icon"></i> customers messages -->
<!--                                             </li> -->
<!--                                         </a> -->
<!--                                         <a href="#"> -->
<!--                                             <li class="list-group-item message"> -->
<!--                                                 view all -->
<!--                                             </li> -->
<!--                                         </a> -->
<!--                                     </ul> -->
<!--                                 </li> -->
<!--                             </ul> -->
<!--                         </li> -->
<!--                         <li class="dropdown profile"> -->
<!--                             <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Emily Hart <span class="caret"></span></a> -->
<!--                             <ul class="dropdown-menu animated fadeInDown"> -->
<!--                                 <li class="profile-img"> -->
<!--                                     <img src="/static/motorapp/img/profile/picjumbo.com_HNCK4153_resize.jpg" class="profile-img"> -->
<!--                                 </li> -->
<!--                                 <li> -->
<!--                                     <div class="profile-info"> -->
<!--                                         <h4 class="username">Emily Hart</h4> -->
<!--                                         <p>emily_hart@email.com</p> -->
<!--                                         <div class="btn-group margin-bottom-2x" role="group"> -->
<!--                                             <button type="button" class="btn btn-default"><i class="fa fa-user"></i> Profile</button> -->
<!--                                             <button type="button" class="btn btn-default"><i class="fa fa-sign-out"></i> Logout</button> -->
<!--                                         </div> -->
<!--                                     </div> -->
<!--                                 </li> -->
<!--                             </ul> -->
<!--                         </li> -->
<!--                     </ul> -->
<!--                 </div> -->
            </nav>
            <div class="side-menu">
                <!-- <nav class="navbar navbar-default" role="navigation">
                    <div class="side-menu-container">
                        <div class="navbar-header">
                            <a class="navbar-brand" href="#">
                                <div class="icon fa fa-anchor"></div>
                                <div class="title">LearnKit</div>
                            </a>
                            <button type="button" class="navbar-expand-toggle pull-right visible-xs">
                                <i class="fa fa-times icon"></i>
                            </button>
                        </div>
                        <ul class="nav navbar-nav">
                            <li>
                                <a href="../index.html">
                                    <span class="icon fa fa-tachometer"></span><span class="title">Dashboard</span>
                                </a>
                            </li>
                            <li class="panel panel-default dropdown">
                                <a data-toggle="collapse" href="#dropdown-element">
                                    <span class="icon fa fa-desktop"></span><span class="title">UI Kits</span>
                                </a>
                                <!-- Dropdown level 1 -->
                                <div id="dropdown-element" class="panel-collapse collapse">
                                    <div class="panel-body">
                                        <ul class="nav navbar-nav">
                                            <li><a href="/static/motorapp/ui-kits/grid.html">Grid</a>
                                            </li>
                                            <li><a href="/static/motorapp/ui-kits/button.html">Buttons</a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>  
                    <!-- /.navbar-collapse -->
                </nav> -->
            </div> 
            <!-- Main Content -->
            <div class="container-fluid">
                <div class="side-body">
                    <div class="page-title">
                        <span class="title">{% block header %} {% endblock header %}</span>
                    </div>
                    <div class="row">
                        {% block content %}

                        {% endblock content %}
                    </div>
                </div>
            </div>
        </div>
        <footer class="app-footer">
            <div class="wrapper">
                <span class="pull-right">0.0 <a href=""><i class="fa fa-long-arrow-up"></i></a></span>2015 LearnKit.
            </div>
        </footer>
    <div>
    <!-- Javascript Libs -->
    <script type="text/javascript" src="/static/motorapp/bower_components/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="/static/motorapp/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/static/motorapp/bower_components/chartjs/Chart.min.js"></script>
    <script type="text/javascript" src="/static/motorapp/bower_components/bootstrap-switch/dist/js/bootstrap-switch.min.js"></script>
    <script type="text/javascript" src="/static/motorapp/bower_components/iCheck/icheck.min.js"></script>
    <script type="text/javascript" src="/static/motorapp/bower_components/matchHeight/jquery.matchHeight-min.js"></script>
    <script type="text/javascript" src="/static/motorapp/bower_components/DataTables/media/js/jquery.dataTables.min.js"></script>
            <script type="text/javascript" src="/static/motorapp/bower_components/select2/dist/js/select2.full.min.js"></script>
            
    <script type="text/javascript" src="/static/motorapp/vendor/js/dataTables.bootstrap.js"></script>
    <script type="text/javascript" src="/static/motorapp/vendor/js/ace/ace.js"></script>
    <script type="text/javascript" src="/static/motorapp/vendor/js/ace/mode-html.js"></script>
    <script type="text/javascript" src="/static/motorapp/vendor/js/ace/theme-github.js"></script>
    <!-- Javascript -->
    <script type="text/javascript" src="/static/motorapp/js/app.js"></script>

    <!--script for this page-->

    {% block scripts %}

    {% endblock scripts %}
</body>

</html>